### ISSUE TITLE
migrate to travis-ci.com

### ISSUE THREAD

**Issue by drewgilliam** [vxl/vxl#837]
travis-ci.org will be shutting down very soon.  Can someone with the right permissions migrate CI to travis-ci.com?
https://docs.travis-ci.com/user/migrate/open-source-repository-migration

@hjmjohnson @decrispell

**Comment by decrispell** [comment]
I tried to do this, but it appears I don't have the proper permissions.  I believe it requires an "owner" (@mleotta, @bradking).

**Comment by bradking** [comment]
I approved the updated TravisCI integration.

**Comment by drewgilliam** [comment]
I don't believe the migration to travis-ci.com was completed?  PRs are not building, travis-ci.org is officially depreciated

https://travis-ci.org/github/vxl/vxl
![image](https://user-images.githubusercontent.com/17988826/122816338-97e88680-d2a4-11eb-887f-b78fef5f1519.png)

https://travis-ci.com/github/vxl/vxl
<img src="https://user-images.githubusercontent.com/17988826/122816406-acc51a00-d2a4-11eb-8041-113fc6d341ae.png"  width=256>

**Comment by decrispell** [comment]
It appears some more action from a vxl admin is still required.  If I go here:  https://travis-ci.com/organizations/vxl/migrate,  I cannot select vxl until the vxl organization signs up for beta (green button on bottom).

![image](https://user-images.githubusercontent.com/1390275/122818916-c156e180-d2a7-11eb-9c27-50f041402e12.png)

**Comment by mleotta** [comment]
@decrispell I think what was missing was signing up for the free plan, which I've just done.  I think it should work now.  However, the new Travis-CI is much less open source friendly than it used to be.  There are a limited number of "credits" per month we get for free to run CI jobs and if you use them up your CI stops.  Open source projects can request additional free credits, but only if the project development is not sponsored by any companies.  VXL would not qualify for that.  Let's see how quickly we burn through credits, but it might be time to switch to a different service, like Circle CI.

**Comment by decrispell** [comment]
Thanks - As far as I can tell, vxl was not actually migrated to travis-ci.com, though.  I still see the same screen as above.

**Comment by bradking** [comment]
I just ran the migration.

**Comment by decrispell** [comment]
Thanks @bradking @mleotta !  Looks like its working now.
